schema_version = 1
rust_toolchain = "1.97.1"

[tools]
cargo-nextest = "0.9.118"
cargo-hack = "0.6.39"
cargo-machete = "0.8.0"
cargo-deny = "0.18.5"
cargo-audit = "0.22.2"
cargo-vet = "0.10.2"
cargo-cyclonedx = "0.5.7"
cargo-about = "0.8.4"
cargo-auditable = "0.7.2"
cargo-llvm-cov = "0.6.21"
cargo-mutants = "26.0.1"
cargo-fuzz = "0.13.1"
cargo-dist = "0.30.3"
cargo-deb = "3.6.2"
mdbook = "0.4.52"

[commands]
cargo-vet = "cargo vet check"
