[package]
name = "lantern-app"
description = "Application use cases and ports for VFD Lantern"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
lantern-domain.workspace = true
lantern-profile.workspace = true

[lints]
workspace = true
